// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLVt-zGa2Dc0ebZM2Rpci-8ae1nv2Qrgg',
    appId: '1:750522534385:web:b4958b3c53a370a9379c50',
    messagingSenderId: '750522534385',
    projectId: 'jungle-7bb06',
    authDomain: 'jungle-7bb06.firebaseapp.com',
    storageBucket: 'jungle-7bb06.firebasestorage.app',
    measurementId: 'G-0S7MDV5GYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNRKLEftIPBt2mvLL1hgHxAcT8DXiGmqM',
    appId: '1:750522534385:android:7006920776646a87379c50',
    messagingSenderId: '750522534385',
    projectId: 'jungle-7bb06',
    storageBucket: 'jungle-7bb06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsIf9eYjQpcvAYedDEDCWWuyCds12GfJY',
    appId: '1:750522534385:ios:0e693cede421b81b379c50',
    messagingSenderId: '750522534385',
    projectId: 'jungle-7bb06',
    storageBucket: 'jungle-7bb06.firebasestorage.app',
    iosBundleId: 'com.example.jungleMemos',
  );
}
